name: 00-Deploy Bare Infrastructure

on:
  workflow_dispatch

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_TERRAFORM_BACKEND_BUCKET: ${{ secrets.S3_TERRAFORM_BACKEND_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/mlops-github-actions-role

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.15.2

      - name: Initialize Terraform
        run: terraform init -backend-config="use_lockfile=false" -backend-config="bucket=${{ env.S3_TERRAFORM_BACKEND_BUCKET }}" 

      - name: Plan Terraform
        run: terraform plan -out=tfplan -var="mlops-users={}"

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan