name: 99-Destroy Infrastructure

on:
  workflow_dispatch

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_TERRAFORM_BACKEND_BUCKET: ${{ secrets.S3_TERRAFORM_BACKEND_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/mlops-github-actions-role

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.15.2

      - name: Destroy Terraform
        run: terraform destroy -auto-approve -backend-config="bucket=${{ env.S3_TERRAFORM_BACKEND_BUCKET }}"